package common

const (
	READ_DB  int8 = 1
	WRITE_DB      = 2
)

const (
	BUILD_DEBUG   int8 = 1
	BUILD_RELEASE int8 = 0
	BUILD_TEST    int8 = 0
)

const (
	PATH_SEPARATOR_LINUX       = '/'
	PATH_SEPARATOR_WINDOWS     = '\\'
	DEFAULT_PATH_SEPARATOR     = PATH_SEPARATOR_WINDOWS
	PATHLIST_SEPARATOR_LINUX   = ':'
	PATHLIST_SEPARATOR_WINDOWS = ';'
	DEFAULT_PATHLIST_SEPARATOR = PATHLIST_SEPARATOR_LINUX
)
