vesrion: 1.0
server:
  host: 0.0.0.0
  port: 8086
  timeout: 60
  max_connections: 100
  max_idle_connections: 10
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  max_header_bytes: 1048576
  max_body_bytes: 1048576
  max_header_count: 100
  max_body_count: 100
  
repo:
  databases:
    oracle:
      read:
        ebatest:
          user: ebatest
          password: ebatest
          host: 0.0.0.0
          port: 2227
          db: ebatest
          schema: ebatest
      write:
        ebatest:
          user: ebatest
          password: ebatest
          host: 0.0.0.0
          port: 2227
          db: ebatest
          schema: ebatest
  redis:
    host: 0.0.0.0
    port: 6389
log:
  path: "auto_app_dev.log"
  level: -1
